#! /bin/sh

echo "INSTALL dependencies for BLOGz"

pip install -U tzlocal
pip install -U pytz
pip install -U flask
pip install -U flask_sqlalchemy
pip install -U flask-bcrypt
pip install -U pymysql


