#! /bin/bash

#NOTE: should be run from project root

echo "INIT::ALL for BLOGz"


if [[ -d util ]]
then
# Do first as password is required
util/init_dbenv

# Order here matters!
util/init_virtualenv
util/init_pydep
util/init_models
else
echo "Unable to run script from this location."
echo "Are you in project root?"
fi
