#! /bin/sh

#NOTE: should be run from project root

echo "INSTALL python dependencies for BLOGz"
echo "  using Virtual Environment 'mega'"

bash -c "source mega/bin/activate; pip3 install -q -U --compile -r depends; exit"