#! /bin/bash

#NOTE: should be run from project root

echo "INIT Virtual Environment 'mega' @ `pwd`"

if [[ -d util ]]
then
virtualenv --python=python3 --system-site-packages --always-copy -v mega
else
echo "Unable to run script from this location."
echo "Are you in project root?"
fi

