#! /bin/bash

#NOTE: should be run from project root

echo "INIT Models (Tables)"

if [[ -d util ]]
then
source mega/bin/activate
python3 models.py
exit
else
echo "Unable to run script from this location."
echo "Are you in project root?"
fi
