#! /bin/bash

#NOTE: should be run from project root
 
if [[ -d util ]]
then
echo "INIT database 'blogz' & user 'blogz@localhost:blogz'"
echo "  NOTE: 'root' login will require password"
echo "EXECUTE QUERIES from 'util/createdb.sql'"

echo -n "MySQL User 'root' => "
mysql -u root -p -v -v -v < util/createdb.sql
else
echo "Unable to run script from this location."
echo "Are you in project root?"
fi
