#! /bin/bash

#NOTE: should be run from project root

echo "REMOVE::ALL for BLOGz"
if [[ -d util ]]
then
util/rm_dbenv
util/rm_virtualenv
else
echo "Unable to run script from this location."
echo "Are you in project root?"
fi
