#! /bin/bash

#NOTE will NOT persist on errors

echo "BLOGz Flask Server - SINGLE USE"
if [[ -d util ]]
then
source mega/bin/activate
python main.py
echo "SERVER is SHUTDOWN"
exit
else
echo "Unable to run script from this location."
echo "Are you in project root?"
fi
